### ISSUE TITLE
not working for ios

### ISSUE THREAD

**Issue by mglkn** [KohlsAdrian/zendesk2#16]
Hi! Thank you for your work. 

I tried to launch your example code (with my zendesk keys) and it work for android, but doesn't  work for ios. Interface is working, but i can't receive any messages from ios client.

flutter sdk: 2.05
IOS deployment target 11.0

**Comment by KohlsAdrian** [comment]
Hi mglkn, thanks for your issue request

I have an open PR about fixing performance on the plugin, I am thinking that should be happening some issues with iOS on the new Flutter 2.0.0+ with the Zendesk SDK and we can't seem to find out what is happening

**Comment by mglkn** [comment]
Ok. Thank you for your quick response.
