### ISSUE TITLE
Android Min version 21

### ISSUE THREAD

**Issue by diegogarciar** [KohlsAdrian/zendesk2#17]
Hello, the [chat docs](https://developer.zendesk.com/embeddables/docs/chat-sdk-v-2-for-android/getting_started) specify that the SDK is compatible with API level 16, is there a specific reason for why it is set to 21?

**Comment by diegogarciar** [comment]
https://github.com/KohlsAdrian/zendesk2/blob/3afddd04c76d5466075db9beea3048a6de57fcab/android/build.gradle#L36

I changed the example to API level 16 and it worked with no problem

**Comment by KohlsAdrian** [comment]
There is no specific reason, as I don't have a development environment I will have to wait till next time I make a new plugin update and I can test lowering the Android min sdk and if it's ok in both platforms using all features, I will release it

**Comment by KohlsAdrian** [comment]
At this moment, please do it locally on your machine and don't delete pubspec.yaml so it won't overwrite from the network

**Comment by diegogarciar** [comment]
Thanks!
