### ISSUE TITLE
In IOS only once open but in android working fine

### ISSUE THREAD

**Issue by Aravind-Tamizh** [KohlsAdrian/zendesk2#2]
Zendesk chat screen natively popped up only once in IOS then no response

**Comment by KohlsAdrian** [comment]
What you mean by no response?
Do you have a log?
You can enable logger for verbose info!
Please provide more information of the issue

**Comment by Aravind-Tamizh** [comment]
`  void zendesk(bool isNativeChat, BuildContext context) async {
    try {
      String accountKey = '${AppConfig.ZendDeskAccountKey}';
      String appId = '';
      String name = '${userPref.userName.val}';
      String email = '${userPref.email.val}';
      String phoneNumber = '${userPref.mobile.val}';
      await z.init(accountKey, appId, iosThemeColor: MyColors.secondaryColor);
      await z.customize(
        departmentFieldStatus: PRE_CHAT_FIELD_STATUS.HIDDEN,
        emailFieldStatus: PRE_CHAT_FIELD_STATUS.HIDDEN,
        nameFieldStatus: PRE_CHAT_FIELD_STATUS.HIDDEN,
        phoneFieldStatus: PRE_CHAT_FIELD_STATUS.HIDDEN,
        transcriptChatEnabled: true,
        agentAvailability: false,
        endChatEnabled: true,
        offlineForms: true,
        preChatForm: true,
        transcript: true,
      );
      await z.setVisitorInfo(
        name: name,
        email: email,
        phoneNumber: phoneNumber,
        tags: ["orderId: ${widget.orders.id}"],
      );

      await z.logger(true);
      if (isNativeChat)
        await z.startChat(
          toolbarTitle: 'Support for Order ${widget.orders.id}',
          backButtonLabel: 'Back',
          botLabel: 'bip bop boting',
        );
    }catch(e){
      print("Zendesk error $e");
    }
  }`

**Comment by Aravind-Tamizh** [comment]
this is my code there is no error in log, chat screen not come

**Comment by KohlsAdrian** [comment]
Your appId is missing

For Zendesk mobile chat to get working you need the AppId too

In the Zendesk panel you must create an app, and get the AppId generated by Zendesk

**Comment by Aravind-Tamizh** [comment]
Now wen have free version of zendesk chat ,   how can we get AppId in zendesk account can u please explain

**Comment by KohlsAdrian** [comment]
Unfortunately Zendesk is paid, you must pay a plan to use this feature

**Comment by KohlsAdrian** [comment]
I am working on a company that have Zendesk plan and as my team is responsible for Flutter development I made the plugin focused on chat and UI customization.
As the SDK request you must have AccountKey and AppId, if you don't have at least the appId too, you can't use this feature. You must contact them if it is possible to user this kind of feature, but for my knowledge this is a paid feature and I can't share my company's keys, because it's a business model.

**Comment by KohlsAdrian** [comment]
The difference of my plugin against the others plugins of Zendesk on pub.dev is that I rely on the most accurate possible SDK life cycle, both on Android and iOS, and my plugin has providers, that has been the most complex and time spent to implement it. 
I had to map every variable and beautify it to Flutter via method channel.
You can make your own Live Chat with a simple stream that I have made

**Comment by KohlsAdrian** [comment]
As long it has no updates I will close this issue.

Is free to reopen it when there is a new update

**Comment by KohlsAdrian** [comment]
@Aravind-Tamizh the issues is fixed on new pub.dev release (1.4.1)

If you still want to use the native chat (deprecated) you can use it now as it is fixed by now

Thanks for your patience
