### ISSUE TITLE
Push notifications on Android

### ISSUE THREAD

**Issue by urusai88** [KohlsAdrian/zendesk2#23]
Hello
I added this
```xml
<service
    android:name=".MainMessagingService"
    android:exported="false">
    <intent-filter>
        <action android:name="com.google.firebase.MESSAGING_EVENT" />
    </intent-filter>
</service>
```
created this
```kotlin
class MainMessagingService : FirebaseMessagingService() {
    override fun onNewToken(p0: String) {
        super.onNewToken(p0)
        print("onNewToken $p0")
    }

    override fun onMessageReceived(p0: RemoteMessage) {
        super.onMessageReceived(p0)
        print("onMessageReceived $p0")
    }
}
```
and called this
```dart
final fcmToken = await FirebaseMessaging.instance.getToken();
if (fcmToken != null) {
  await z.registerFCMToken(fcmToken);
}
```
but device does not receive zendesk notifications
also methods of my MainMessagingService does not called when i sent a push to my device manually via FCM. 
What configuration did i miss?

**Comment by urusai88** [comment]
I connected fcm with app correctly
The problem is i can't override com.google.firebase.MESSAGING_EVENT with my .MainMessagingService service
App receive a push from FCM and from Zendesk, but i can't manually handle what do with this push. For example, i can't show notification to user when application in background

**Comment by KohlsAdrian** [comment]
FCM message you have to handle with firebase plugin, not with zendesk2 plugin

check this example: https://pub.dev/packages/firebase_messaging/example

**Comment by urusai88** [comment]
I want, but my FirebaseMessagingService does not handle incoming message

**Comment by KohlsAdrian** [comment]
Please check the example mentioned above, you should not only map FCM integration in native side, you should do that in Flutter/dart code too, fcm plugin provides onMessage callbacks
