### ISSUE TITLE
ZendeskChat

### ISSUE THREAD

**Issue by Crewlan** [KohlsAdrian/zendesk2#27]
Hi @KohlsAdrian , can you help me, I'm trying to implement zendesk chat in a project, however when calling the start chat providers function, however the provider model and agent returns null, I checked in the zendesk panel and in the implementation and it gives me a URL in initialize, can you help me if I really need this URL at initialize?

**Comment by KohlsAdrian** [comment]
No you don't need the URL

you need accountKey and appID

AppID you can get here: https://yourdomain.zendesk.com/agent/admin/mobile_sdk

AccountKey you can get here: https://yourdomain.zendesk.com/chat/agent#home > Profile Picture > Check Connection

**Comment by Crewlan** [comment]
Thanks @KohlsAdrian  it's worked with you links
