### ISSUE TITLE
[NATIVE CHAT][OBSOLETE] cannot use the chat bot

### ISSUE THREAD

**Issue by minhduc1827** [KohlsAdrian/zendesk2#31]
Hello,
it's a great library about the zendesk.
 Now,i cannot turn on the chat bot in your library

**Comment by KohlsAdrian** [comment]
Please give more details

**Comment by minhduc1827** [comment]
![image](https://user-images.githubusercontent.com/4393681/133426804-6df61444-cf5b-46d0-a312-7657779357c7.png)

**Comment by minhduc1827** [comment]
In the previos zendesk sdk, i saw that it had it.
https://support.zendesk.com/hc/en-us/articles/360053016333-Why-do-I-see-the-Answer-Bot-in-the-Chat-SDK-even-though-I-don-t-have-a-subscription-

**Comment by KohlsAdrian** [comment]
I see that you are using the 1.3.0 version. Native chat is removed in 2.0.0+
As of version <2.0.0 of the plugin, native chat is obsolete and discouraged to use. You may use Providers and create your own custom UI.

Please see the `./example` folder on how to achieve it on local pub files on the 1.3.0 plugin folder

**Comment by KohlsAdrian** [comment]
Download the plugin 1.3.0 source code (https://storage.googleapis.com/pub-packages/packages/zendesk2-1.3.0.tar.gz)

And open the /example folder to test the demo and see how it works with custom providers

**Comment by minhduc1827** [comment]
But if i use native chat, can i customize the bot icon chat, text font size and font family...

**Comment by KohlsAdrian** [comment]
You should not use native chat, is unstable and buggy

**Comment by minhduc1827** [comment]
But if i don't use native chat, i cannot use the bot chat

**Comment by KohlsAdrian** [comment]
You can use triggers in Zendesk

**Comment by KohlsAdrian** [comment]
https://support.zendesk.com/hc/en-us/articles/360022365873-Zendesk-Chat-triggers-conditions-and-actions-reference

**Comment by minhduc1827** [comment]
So, does this function exist in your library?

**Comment by KohlsAdrian** [comment]
Triggers are set in Zendesk, not in the plugin, I will close this issue because Native Chat is Obsolete and discouraged to use
