### ISSUE TITLE
iOS do not receive messages

### ISSUE THREAD

**Issue by mondoktamas** [KohlsAdrian/zendesk2#32]
Hello! I started your example app on my iOS device and the Chat SDK works incorrectly. I do not receive any message sent from Zendesk Web Panel. It seems something breaks the message receiving logic after Support joins the conversation.
Also the same example app works correctly on android.

Can you please help how can i solve the problem on iOS?

**Comment by KohlsAdrian** [comment]
Please provide more details

**Comment by mondoktamas** [comment]
@KohlsAdrian I started your example app on iOS. Pressed on the Chat SDK V2 button, which opened the chat page. I (as Visitor) could send messages from the mobile device until the Support joins the chat (on zendesk web panel). After the Support accepts and opens the chat with the Visitor, the Visitor stops receiving any messages from the Support sent from the web panel. Even the new messages sent by the Visitor will not be displayed in the app.

https://www.dropbox.com/s/x07ibqsejvaw3y5/Screen%20Recording%202021-09-15%20at%2017.20.24.mov?dl=0

**Comment by KohlsAdrian** [comment]
Ok, I'll check it out later

**Comment by KohlsAdrian** [comment]
I can't seem to find the issue.
What is the version of the plugin you are using

**Comment by mondoktamas** [comment]
@KohlsAdrian with version 2.0.0+1 issue seems to be disappeared. I'm closing this issue. Thanks
