### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by mauriciorzm** [KohlsAdrian/zendesk2#5]
The plugin won't work, I get this error message.

e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\zendesk2-1.2.1\android\src\main\kotlin\br\com\adriankohls\zendesk2\Zendesk2Chat.kt: (78, 67): Expecting an argument

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':zendesk2:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7m 4s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Comment by KohlsAdrian** [comment]
Have you tried `flutter clean` before compiling the app?

**Comment by KohlsAdrian** [comment]
As long as there is no more information or updates about the issue I will close it here, it will be possible to reopen it if necessary
