### ISSUE TITLE
On Android, when reopening chat history clear

### ISSUE THREAD

**Issue by VolodymyrZhuravlovRacoon** [KohlsAdrian/zendesk2#6]
On Android, when reopening chat, the messages that I previously wrote are not displayed. More precisely, they are visible for a fraction of a second and then disappear. Everything works well on IOS

**Comment by KohlsAdrian** [comment]
I am a little busy with business, there is a sprint job for Zendesk on my side and this issue is pointed to fix. 
Please be patient

**Comment by KohlsAdrian** [comment]
https://github.com/KohlsAdrian/zendesk2/pull/7

**Comment by KohlsAdrian** [comment]
Released on pub.dev as version 1.3.0
