### ISSUE TITLE
Execution failed for task ':zendesk2:compileDebugKotlin'.

### ISSUE THREAD

**Issue by emren** [KohlsAdrian/zendesk2#8]
Dear Adrian
I get this error running from start. I tried flutter clean, different versions of your package, deleting .gradle file and same result. Here is the full error: 

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':zendesk2:compileDebugKotlin'.
> Compilation error. See log for more details

My gradle setting is verbose so I receive the following: 
> :app:checkDebugAarMetadata > Resolve files of :app:debugRuntimeClasspath > Tr> :app:checkDebugAarMetadata > Resolve files of :app:debugRuntimeClasspath > Tr> :app:checkDebugAarMetadata > Resolve files of :app:debugRuntimeClasspath > Tr> :app:checkDebugAarMetadata > Resolve files of :app:debugRuntimeClasspath > Tr<==-----------> 19% EXECUTING [52s]> :package_info:packageDebugAssets> IDLE> IDLE> IDLE<===----------> 23% EXECUTING [52s]> :app:copyFlutterAssetsDebug<===----------> 23% EXECUTING [53s]<====---------> 33% EXECUTING [53s]> :app:mergeDebugResources > Resolve files of :app:debugRuntimeClasspath > Tran> :app:mergeDebugResources > Resolve files of :app:debugRuntimeClasspath > Tran> :app:mergeDebugResources > Resolve files of :app:debugRuntimeClasspath > Tran> :app:mergeDebugResources > Resolve files of :app:debugRuntimeClasspath > Tran<=====--------> 38% EXECUTING [53s]> IDLE> :app:processDebugMainManifest > Resolve files of :app:debugRuntimeClasspath >> :app:processDebugMainManifest > Resolve files of :app:debugRuntimeClasspath >> :app:processDebugMainManifest > Resolve files of :app:debugRuntimeClasspath ><=====--------> 40% EXECUTING [53s]> IDLE> :firebase_core:generateDebugRFile > Resolve dependencies of :firebase_core:de> IDLE<=====--------> 41% EXECUTING [53s]> :firebase_performance:generateDebugRFile > Resolve files of :firebase_perform> :firebase_performance:generateDebugRFile > Resolve files of :firebase_perform> :firebase_performance:generateDebugRFile > Resolve files of :firebase_perform> :firebase_performance:generateDebugRFile > Resolve files of :firebase_perform<=====--------> 42% EXECUTING [53s]> :image_picker:generateDebugRFile > Resolve dependencies of :image_picker:debu> IDLE> IDLE> IDLE<=====--------> 44% EXECUTING [53s]> IDLE<=====--------> 45% EXECUTING [53s]> :video_player:generateDebugRFile > Resolve files of :video_player:debugCompil<======-------> 46% EXECUTING [54s]> :zendesk2:generateDebugRFile > Resolve files of :zendesk2:debugCompileClasspa> :app:processDebugResources > Resolve dependencies of :app:debugCompileClasspa<======-------> 49% EXECUTING [54s]> :firebase_dynamic_links:compileDebugJavaWithJavac > Resolve files of :firebas> :firebase_dynamic_links:compileDebugJavaWithJavac > Resolve files of :firebas<=======------> 54% EXECUTING [54s]> :video_player:bundleLibCompileToJarDebug> IDLE<=======------> 56% EXECUTING [54s]> :zendesk2:compileDebugKotlin<=======------> 56% EXECUTING [55s]<=======------> 56% EXECUTING [55s]> IDLE<-------------> 0% WAITING
Exception: Gradle task assembleDebug failed with exit code 1

My flutter doctor is:[✓] Flutter (Channel stable, 2.0.3, on macOS 11.2.3 20D91 darwin-x64, locale en-TR)
    • Flutter version 2.0.3 at /Users/emrenizamoglu/Developer/flutter
    • Framework revision 4d7946a68d (8 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/emrenizamoglu/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (2 available)
    • AOSP on IA Emulator (mobile) • emulator-5554 • android-x86    • Android 9 (API 28) (emulator)
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 89.0.4389.90

• No issues found!

**Comment by KohlsAdrian** [comment]
Got it, I'll take a look later, I tested on Flutter 2.0.2 and it worked fine.

Did you try cleaning your .pub cache and downloading packages again?

**Comment by emren** [comment]
Hi Adrian, 
I opened a clean branch and setup again.
IDE gives me this error

Running Gradle task 'assembleDebug'...
e: /Users/emrenizamoglu/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/zendesk2-1.4.0/android/src/main/kotlin/br/com/adriankohls/zendesk2/Zendesk2Chat.kt: (76, 67): Expecting an argument

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':zendesk2:compileDebugKotlin'.
> Compilation error. See log for more details

**Comment by KohlsAdrian** [comment]
That's weird, I cannot replicate your issue, all my plugin seems fine on null-safety and on non null-safety

**Comment by canturkay** [comment]
I'm also facing the same issue. I receive the following error while building for Android (minSdkVersion 21) on Windows:

Pub\Cache\hosted\pub.dartlang.org\zendesk2-1.4.0\android\src\main\kotlin\br\com\adriankohls
\zendesk2\Zendesk2Chat.kt: (76, 67): Expecting an argument
[  +10 ms] FAILURE: Build failed with an exception.
[   +2 ms] * What went wrong:
[   +1 ms] Execution failed for task ':zendesk2:compileDebugKotlin'.
[   +1 ms] > Compilation error. See log for more details
[   +1 ms] * Try:
[  +24 ms] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log
output. Run with --scan to get full insights.
[   +5 ms] * Get more help at https://help.gradle.org
[   +2 ms] BUILD FAILED in 1m 14s
[ +508 ms] Running Gradle task 'assembleDebug'... (completed in 75.8s)
[   +7 ms] Exception: Gradle task assembleDebug failed with exit code 1

My flutter version is 2.0.3 with null-safety disabled. I'm using the latest stable release for Kotlin (1.4.31-release-Studio4.1-1).

**Comment by KohlsAdrian** [comment]
thanks for the PR

released on pub.dev as  `1.4.0+1`
